### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by barskern** [VegardSkaansar/IMT-2681-Cloud-Technologies#1]
I've noted down my comments from the peer review, so here they come :smile:

# Peer review

Performed the 23.10.2018 on commit `69eab7ceef649f37d374dcae6331bb8e15e17baa`.

# Errors

## Invalid field names

Most field names are not named the same as the spec defines:

- For `GET /api/igc/<id>/<field>`
    - `H_date` is named `date`
    - `glider` is named `glidertype`
    - `glider_id` is named `gliderid`
    - `track_length` is named `tracklength`

- For `GET /api/igc/<id>`
    - `H_date` is named `hdate`
    - `gilder_id` is named `gliderid`
    - `track_length` is named `tracklength`

## Inconsistent field names

Field names are inconsistent in the following situations:

- `glider` field in the JSON object is called `glidertype` when requested as a field in the url
- `hdate` field in the JSON object is called `date` when requested as a field in the url

## Invalid response status on invalid field

When some requests are made with invalid input, the response is a 200 status with a empty body. This is the case for:

- `GET /igcinfo/api/igc/0/<rubbish>`
- `GET /igcinfo/api/<rubbish>`

## Only able to POST one url

When an attempt to post a second, different url, the response is: "URL already exists. Use PUT to modify". Looked into the code and the following is done on every `POST` request:

```go
var i IgcURL
_, ok := GlobalDb.GetURL(i.ID)
```

Since `i` is initialized as a empty `IgcURL` struct the value of `i.ID` will always be zero, which is the default value for an `int`, hence one cannot add multiple urls because it will always try to add a `url` with the `id` of zero.

## ID not returned from track registration

When a track is registered the response is supposed to be:

```json
{
    "id": <id>
}
```

Currently the response is a 200 status with a empty body.

## Invalid content type for JSON payloads

Some JSON payloads have a content-type of `text/plain`. This is the case for:

- `GET /igcinfo/api/igc`
- `GET /igcinfo/api/igc/<id>`

## Buggy response on single track request

When `GET /igcinfo/api/igc/a` is requested after a single track has been registered, the server returns both an error and the content of track with an id of zero as follows:

```
This is not possible to convert
{
"hdate":"2016-02-19 00:00:00 +0000 UTC",
"pilot":"Miguel Angel Gordillo",
"glider":"RV8",
"gliderid":"EC-XLL",
"tracklength":443.2573603705269
}
```

The following code is to "blame".

```go
if err != nil {
    http.Error(w, "This is not possible to convert", http.StatusBadRequest)
}
oneURL(w, GlobalDb, number)
```
Here the error code and body is written to the `ResponseBuilder`, but the execution continues as normal, hence the server processes the request as if it was valid.

To resolve this error one could e.g do the following:

```go
if err != nil {
    http.Error(w, "This is not possible to convert", http.StatusBadRequest)
    return
}
oneURL(w, GlobalDb, number)
```

# Tasks

1.	Rubbish URLs are handled correctly (no crashes, proper error messages)
2.	GET /api calls returns an expected JSON struct
3.	In GET /api the return "uptime" is formatted correctly
4.	POST /api/igc works and returns correct return code and body
5.	GET /api/igc returns the correct body and return code
6.	GET /api/igc/<id> returns details of a given track, and correct error value if the <id> is wrong
7.	GET /api/igc/<id>/<field> works for various combination of <id> and <field> values:  pilot, glider, glider_id, track_length, H_date
8.	GET /api/igc/<id>/<field> returns correct error codes when wrong <id> or wrong <field> are used
9.	The code is in a git repo and there is README.md file in the top level
10.	The readme file is meaningful and follows typical open source template (non-strict, give the other student suggestions what would be nice to improve it) .  The code passes the following without any complains (put in comments, if any complaints, or, let the submittee fix them)
11. go build
12. go vet
13. go fmt
14. go test
15. golint
16. gometalinter -- https://github.com/alecthomas/gometalinter
17.	code coverage (go test -cover)
18.	how many commits the git repo has
19.	how many branches the git repo has
20.	cyclomatic complexity problems (above 15), or other metalinter complains, if any
21.	logging events/errors

# Task specific comments

1. Rubbish urls after `/igcinfo/<rubbish>` are handled properly, but `/igcinfo/api/<rubbish>` returns a status 200 with a empty body
2. `GET /api` works
3. "uptime" is formatted correctly but contains unnecessary elements (days and hours are zero)
4. `POST /api/igc` does not return generated id
5. `GET /api/igc` returns both `url` and generated `id` with `content-type` set to `text/plain`.
6. `GET /api/igc/<id>` returns with wrong fields (`hdate` should be `H_date`, `gliderid` should be `glider_id` and `tracklength` should be `track_length`) and invalid `content-type` which is `text/plain`. Appropriate error code when invalid id which is a number, however when letters are passed there is buggy behaviour (see error section above).
7. `GET /api/igc/<id>/<field>` because of #5 most fields did not return value. Returned values have surrounding quotation marks.
    - `H_date` did not work (`date` returned what `H_date` should have)
    - `glider` did not work (`glidertype` returned what `glider` should have)
    - `glider_id` did not work (`gliderid` returned what `glider_id` should have)
    - `track_length` did not work (`tracklength` returned what `track_length` should have)
8. `GET /api/igc/<id>/<field>` returns status 200 with empty body on invalid field
9. The project is a git repo with a `README.md`
10. `README.md` is a bit skinny but has the most important information
11. OK build
12. OK vet
13. OK fmt
14. OK tests but slow
15. OK lint
16. `gometalinter` complains about cyclomatic complexity of `GetRequest`
17. 47.3% test coverage in igcsdb module
18. 8 commits (comment in `README.md`: "THe reason for low commits is that didnt add my code to any github before everything worked locally on my machine")
19. 1 branch
20. `gometalinter` complains about cyclomatic complexity of `GetRequest`
21. logging consists of 3 `fmt.Println` statements on error conditions

**Comment by VegardSkaansar** [comment]
thx, i forgot to publish my last changes before i handed in. put now should atleast post work
